### ISSUE TITLE
docker 部署后不能选择语言

### ISSUE THREAD

**Issue by brucmao** [Femoon/tts-azure-web#13]
```
version: '3'
services:
  tts-azure-web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SPEECH_KEY=${SPEECH_KEY}
      - SPEECH_REGION=${SPEECH_REGION}
      - NEXT_PUBLIC_MAX_INPUT_LENGTH=${NEXT_PUBLIC_MAX_INPUT_LENGTH}
    restart: unless-stopped
```
右侧选择语言一直是空的，不能选择，

<img width="1231" alt="Image" src="https://github.com/user-attachments/assets/ae2e11f7-98f8-4826-a4a4-052c7d4fbca6" />
